import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
    apisidebar: [
        {
            type: "category",
            label: "cachix",
            items: [
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/cachix-agent-deployment-websocket",
                    label: "Cachix agent deployment websocket",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/cachix-agent-idle-websocket",
                    label: "Cachix agent idle websocket",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/upload-and-activate-a-new-deployment",
                    label: "Upload and activate a new deployment",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-a-tenant-in-cachix-format",
                    label: "Get a tenant in cachix format",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-deployment-overview",
                    label: "Get deployment overview",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/upload-new-cachix-signing-key",
                    label: "Upload new cachix signing key",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/retrieve-new-upload-id",
                    label: "Retrieve new upload ID",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/checks-if-a-given-array-of-narhashes-is-already-cached",
                    label: "Checks if a given array of narhashes is already cached",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/see-logs-of-deployment",
                    label: "See logs of deployment",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/retrieve-upload-url",
                    label: "Retrieve upload url",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/finish-a-given-upload",
                    label: "Finish a given upload",
                    className: "api-method post",
                },
            ],
        },
        {
            type: "category",
            label: "deploy",
            items: [
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/cachix-agent-deployment-websocket",
                    label: "Cachix agent deployment websocket",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/cachix-agent-idle-websocket",
                    label: "Cachix agent idle websocket",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/upload-and-activate-a-new-deployment",
                    label: "Upload and activate a new deployment",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-deployment-overview",
                    label: "Get deployment overview",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/see-logs-of-deployment",
                    label: "See logs of deployment",
                    className: "api-method get",
                },
            ],
        },
        {
            type: "category",
            label: "nix",
            items: [
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-nix-derivation-in-nix-caching-format",
                    label: "Get nix derivation in nix caching format",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-nix-cache-info",
                    label: "Get nix cache info",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/fetch-a-nix-binary",
                    label: "Fetch a nix binary",
                    className: "api-method get",
                },
            ],
        },
        {
            type: "category",
            label: "api/v2/deploy",
            items: [
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/upload-and-activate-a-new-deployment",
                    label: "Upload and activate a new deployment",
                    className: "api-method post",
                },
            ],
        },
        {
            type: "category",
            label: "api/v1/cache",
            items: [
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-a-tenant-in-cachix-format",
                    label: "Get a tenant in cachix format",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/upload-new-cachix-signing-key",
                    label: "Upload new cachix signing key",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/retrieve-new-upload-id",
                    label: "Retrieve new upload ID",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/checks-if-a-given-array-of-narhashes-is-already-cached",
                    label: "Checks if a given array of narhashes is already cached",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/retrieve-upload-url",
                    label: "Retrieve upload url",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/finish-a-given-upload",
                    label: "Finish a given upload",
                    className: "api-method post",
                },
            ],
        },
        {
            type: "category",
            label: "api/v1/deploy",
            items: [
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-deployment-overview",
                    label: "Get deployment overview",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/see-logs-of-deployment",
                    label: "See logs of deployment",
                    className: "api-method get",
                },
            ],
        },
        {
            type: "category",
            label: "api/v1/iglu/upload",
            items: [
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/upload-a-nix-binary",
                    label: "Upload a nix binary",
                    className: "api-method put",
                },
            ],
        },
        {
            type: "category",
            label: "iglu",
            items: [
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/upload-a-nix-binary",
                    label: "Upload a nix binary",
                    className: "api-method put",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/modify-api-key-access",
                    label: "Modify API Key access",
                    className: "api-method patch",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-available-tenants",
                    label: "Get available tenants",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/create-new-api-key",
                    label: "Create new API Key",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/delete-api-key",
                    label: "Delete api key",
                    className: "api-method delete",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/create-a-new-tenant",
                    label: "Create a new tenant",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/search-for-tenants",
                    label: "Search for tenants",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-tenant-information",
                    label: "Get Tenant information",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/update-a-tenant",
                    label: "Update a tenant",
                    className: "api-method patch",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/delete-a-tenant",
                    label: "Delete a tenant",
                    className: "api-method delete",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-access-rule",
                    label: "Get Access Rule",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/delete-access-rule",
                    label: "Delete Access Rule",
                    className: "api-method delete",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/update-access-rule",
                    label: "Update Access Rule",
                    className: "api-method patch",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/create-access-rules",
                    label: "Create access rules",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/search-for-access-rules",
                    label: "Search for access rules",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-registered-api-keys",
                    label: "Get registered API Keys",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-available-signing-keys",
                    label: "Get available signing keys",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/update-signing-key",
                    label: "Update signing key",
                    className: "api-method patch",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/deletes-public-signing-key-tenant-link",
                    label: "Deletes public signing key - tenant link",
                    className: "api-method delete",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-signing-key-information",
                    label: "Get Signing Key information",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-information-about-derivation",
                    label: "Get information about derivation",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/delete-derivation",
                    label: "Delete derivation",
                    className: "api-method delete",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/search-for-derivation",
                    label: "Search for derivation",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/pin-derivation",
                    label: "Pin derivation",
                    className: "api-method get",
                },
            ],
        },
        {
            type: "category",
            label: "api/v1/iglu/rest/keys",
            items: [
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/modify-api-key-access",
                    label: "Modify API Key access",
                    className: "api-method patch",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-available-tenants",
                    label: "Get available tenants",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/create-new-api-key",
                    label: "Create new API Key",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/delete-api-key",
                    label: "Delete api key",
                    className: "api-method delete",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-registered-api-keys",
                    label: "Get registered API Keys",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-available-signing-keys",
                    label: "Get available signing keys",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/update-signing-key",
                    label: "Update signing key",
                    className: "api-method patch",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/deletes-public-signing-key-tenant-link",
                    label: "Deletes public signing key - tenant link",
                    className: "api-method delete",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-signing-key-information",
                    label: "Get Signing Key information",
                    className: "api-method get",
                },
            ],
        },
        {
            type: "category",
            label: "api/v1/iglu/rest/tenants",
            items: [
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/create-a-new-tenant",
                    label: "Create a new tenant",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/search-for-tenants",
                    label: "Search for tenants",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-tenant-information",
                    label: "Get Tenant information",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/update-a-tenant",
                    label: "Update a tenant",
                    className: "api-method patch",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/delete-a-tenant",
                    label: "Delete a tenant",
                    className: "api-method delete",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-access-rule",
                    label: "Get Access Rule",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/delete-access-rule",
                    label: "Delete Access Rule",
                    className: "api-method delete",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/update-access-rule",
                    label: "Update Access Rule",
                    className: "api-method patch",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/create-access-rules",
                    label: "Create access rules",
                    className: "api-method post",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/search-for-access-rules",
                    label: "Search for access rules",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/get-information-about-derivation",
                    label: "Get information about derivation",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/delete-derivation",
                    label: "Delete derivation",
                    className: "api-method delete",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/search-for-derivation",
                    label: "Search for derivation",
                    className: "api-method get",
                },
                {
                    type: "doc",
                    id: "02-cache/04-development/02-restapi/pin-derivation",
                    label: "Pin derivation",
                    className: "api-method get",
                },
            ],
        },
    ],
};

export default sidebar.apisidebar;
